name: "Next CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: yarn install --immutable --immutable-cache --check-cache
    
    - name: Build
      run: yarn dev
